### ISSUE TITLE
Stupid cms not open site in VS 2022

### ISSUE THREAD

**Issue by ednsinf** [fluent-cms/fluent-cms#2] opened 2024-09-28 18:36 UTC
Error on starting a website

The program '[12312] FluentCMS.Blog.exe: Program Trace' has exited with code 0 (0x0).
The program '[12312] FluentCMS.Blog.exe' has exited with code 0 (0x0).

**Comment by fluent-cms** [comment] 2024-10-03 00:01
hi ednsinf, thank you so much for letting me know the issue.
My dev environment is mac + rider. I use tool `ln`.
The issue is fixed in release 0.2.3

**Closed** 2024-10-03 00:01 UTC
